### ISSUE TITLE
.gitignoreに*.sqlite3を追加して欲しい

### ISSUE THREAD

**Issue by hanocha** [pokotyamu/morning-meeting-chart#10]
各々がてきとーにテストしたdbがアップロードされてめんどくさそう。
.gitignoreを上げてしまうのも手ではあるが。

**Comment by pokotyamu** [comment]
ごめんよ、db 系がうまく行けば ci 通ると思って追加してしまったｗ
消しても問題ないっすｗ

**Comment by pokotyamu** [comment]
消したら ci 落ちた

**Comment by hanocha** [comment]
即落ち2コマかって思ってしまったｗ

CI上でのDB初期化を`db:migrate`にしたら直ったのでとりあえず様子見。
