### ISSUE TITLE
 実績管理画面を年＋月単位で管理したい

### ISSUE THREAD

**Issue by hanocha** [pokotyamu/morning-meeting-chart#34]
プレビューで見れるのが、年度＋月で管理したいよねって話。

**Comment by pokotyamu** [comment]
スライドショーの部分もそうなってるかと思ったら、そーではなかった実装になってた

**Comment by hanocha** [comment]
いろいろ考えると年/月/日を別カラムで持っておきたくなる。
少なくとも月を別カラムにするとwhereで探しやすい。

**Comment by hanocha** [comment]
Goalモデルで実現した…はず？Closeしとく。
