### ISSUE TITLE
モデルの仕様

### ISSUE THREAD

**Issue by hanocha** [pokotyamu/morning-meeting-chart#4]
- [x] Teamモデル/teamsテーブル
 - string name, not null
 - int goal, not null
 - relation: progress(1:多)
- [x] Progressモデル/progressesテーブル
 - date start_date, not null
 - int amount, not null
 - relation: topic(1:1)
- [x] Topicモデル/topicsテーブル
 - string content, not null

足りないものは適宜追加してOKですの

**Comment by pokotyamu** [comment]
一応、全部に NOT NULL 制約はつけるつもり

**Comment by hanocha** [comment]
いい加減古くなってきたのでClose。
