### ISSUE TITLE
Q毎のグラフを作成したい

### ISSUE THREAD

**Issue by pokotyamu** [pokotyamu/morning-meeting-chart#49]
別に Q毎じゃなくて、グラフに使うGoal と Progress を選べるようにしたら、通年とか半年とかもイケルと思う

やりたいこと
--

+ Goal をモデルの１つとして切り出して、 Progress と関連を持たせる

![fullsizerender 3](https://cloud.githubusercontent.com/assets/3479317/17200751/f2b2e05c-54c2-11e6-98c5-f60eb09074cb.jpg)

+ プレビューでは、最新の月に紐付いた Progress からグラフを作成する
+ 新たにグラフ作成画面を作る
   + 箇条書きのチェックボックスから、選択した月に紐づく Progress でグラフを作成する

![fullsizerender 2](https://cloud.githubusercontent.com/assets/3479317/17200762/ff028f4c-54c2-11e6-99c9-a528dfddbae7.jpg)

**Comment by hanocha** [comment]
できてるので閉じる
