### ISSUE TITLE
Goalモデル追加の流れ

### ISSUE THREAD

**Issue by hanocha** [pokotyamu/morning-meeting-chart#60]
### 方針

* ダウンタイムは基本発生させない
* 今持っているデータが消えないようにする
* スクショから復旧したりとかは極力しない
  * 可能な限りスクリプトとかで自動移行できるようにしたい

### 流れ

* [ ] `Goal`モデル、テーブルを作る
* [ ] `Progresses`テーブルに`goal_id`カラムを追加する
* [ ] `Progresses`テーブルの各レコード、`goal_id`に適切な値を入れる
* [ ] 画面や各種の参照で`Goal`モデルを使うように切り替える
* [ ] 安定動作を確認後、不要なリレーションなどを削除する

**Comment by pokotyamu** [comment]
これやるなら、今の #50 とは別の PR  で、`Goal モデルテーブルを作る` と `Progress テーブルに goal_id カラムを追加する` ってのをやる必要がありそう

**Comment by hanocha** [comment]
とりあえず終わったのでClose。
