### ISSUE TITLE
Qiita 投稿ボタン

### ISSUE THREAD

**Issue by pokotyamu** [pokotyamu/morning-meeting-chart#8]
朝会終わった後にボタン押したら、Qiita に勝手に投稿してくれたら Happy じゃん！！！！！

**Comment by pokotyamu** [comment]
[Qiita API v2ドキュメント - Qiita:Developer](https://qiita.com/api/v2/docs)
これの POST 使ったらなんかできそうな気がしている

**Comment by otofu-square** [comment]
これやりたいっす 👍 
どんな記事が投稿されるかイメージ教えてもらっても良いですか？:pray:

**Comment by otofu-square** [comment]
a-know 氏の [コレ](http://blog.a-know.me/entry/2016/01/09/222210
) と、
Qiita記事の[コレ](http://qiita.com/laiso/items/d5a8a14631025da61bb5)を参考にすれば実装できそう 😄 

記事の投稿自体はえーちゃんが挙げてくれた Qiita API v2 の `POST /api/v2/items` を使って実現できそう 👍

**Comment by otofu-square** [comment]
- SVG が埋め込める場合

GraphCreator モデルを使ってタグが生成できるので、新たにQiitaに貼るグラフを保存しておく場所を用意する必要は無いはず

- SVGが埋め込めない場合

GraphCreator モデルで生成される SVG を画像化する必要があり、更にそれを保存しておく場所を作る必要がある
Qiita からその画像を参照するには外部からその画像に対してURLでアクセスできる必要もありそう

**Comment by otofu-square** [comment]
Qiita 記事に svg を直接インラインHTMLで埋め込めないか試してみたけどダメだった…
なので SVG を画像化してサーバサイドで保存して、 その画像の URL を Markdown に埋め込むのが一番現実的かな… :cry:

**Comment by otofu-square** [comment]
そもそも外部公開しないとはいえ、グラフをURLでアクセスできるようにするのはまずい気がしてきた
更にQiitaへの画像アップロードはAPIを経由して出来ないので（ドラッグ&ドロップでしかアップロード出来ない…）開始早々に詰んでしまった気がする…

**Comment by hanocha** [comment]
> そもそも外部公開しないとはいえ、グラフをURLでアクセスできるようにするのはまずい気がしてきた

グラフ閲覧に対しては…どーだろ、ローカルにhighchartを持ってきて、そこで動かすようにできれば
1つ目の問題点はどうにかならなくもない…気がする。
https://shop.highsoft.com/highcharts/
（どこまで非営利として見られるか微妙だけど）

二つ目は…マジか…うーん…

**Comment by otofu-square** [comment]
> ローカルにhighchartを持ってきて、そこで動かすようにできれば

Qiita上 で highchart を動かすって意味かな？ :eyes:

**Comment by otofu-square** [comment]
とりあえずテンプレートのテキストを Qiita に投稿するだけの機能を作る、という話をした 👍

**Comment by pokotyamu** [comment]
１番いいマークダウンで頼む

**Comment by pokotyamu** [comment]
_ついでにグラフのフォントがダウンロードしたら変わっちゃう問題も解決してくれると嬉しい_

**Comment by pokotyamu** [comment]
@otofu-square 今日、歩きながら思ったけど、投稿するのにわざわざボタンで実装せずに、裏で cron で実行される方が嬉しい気がしてきた。
`whenever` とか使えば行けそうな気がしている https://github.com/javan/whenever

**Comment by otofu-square** [comment]
いいと思います  👍 
ただ、せっかくHeroku使ってるので [Heroku Scheduler](https://devcenter.heroku.com/articles/scheduler) でいいかもしれない

**Comment by pokotyamu** [comment]
これって課金発生する？

**Comment by otofu-square** [comment]
頻繁に動かさない限りは無料枠の範囲に収まると思う！
Heroku Scheduler が稼働している時間が Dyno Hours に加算されていく感じみたいですね

**Comment by pokotyamu** [comment]
じゃあ、なおさら自動化したいね！
そこら辺の調査含めてオナシャス！
金曜までにリリース出来たら、記事に合わせて載せれる！←

**Comment by otofu-square** [comment]
とても簡単にAPIにアクセスできるので [qiita-rb](https://github.com/increments/qiita-rb) を使う予定
もはやAPIを弄っていることを忘れさせてくれるぐらい簡単に利用できそう

```
require 'qiita'

client = Qiita::Client.new(access_token: ENV["QIITA_API_KEY"])

client.list_items
client.list_users
client.list_user_items("otofu_square")
client.get_user("otofu_square")
```

今思ったけど投稿のテストが結構し辛そう…
Qiita:team の方だと Slack の通知が飛んでしまうので乱発は避けたい
アプリから飛ぶAPIのリクエストの中身を確認して問題がなさそうなのを十分確認してからテストするようにしよう

**Comment by pokotyamu** [comment]
> 今思ったけど投稿のテストが結構し辛そう…

ひとまず、文字整形できるようになったら１回みんなで確認とかでいいんじゃないかな？
あとは、rand チャンネルで事前通知(？)

**Comment by hanocha** [comment]
> 投稿するのにわざわざボタンで実装せずに、裏で cron で実行される方が嬉しい気がしてきた。

#66 で一旦完結？ボタンじゃなくなってるけどいいんだよね。
